username: kingbeful
baseurl: /space
markdown: redcarpet
safe: false
highlighter: pygments
title: Kevin's Code Log
description: Freedom is the Most Important Thing
theme: kunka
disqusname: minixalpha

# prev theme is: modernist
# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine
# those themes are all come from GitHub Pages Themes
